/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculadora_Divisas;

import java.text.DecimalFormat;

/**
 *
 * @author franc
 */
public class Calculador_De_Divisas extends javax.swing.JFrame {

    /**
     * Creates new form Calculador_De_Divisas
     */
    public Calculador_De_Divisas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Importe = new javax.swing.JTextField();
        Moneda_De_Importe = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Moneda_Conversion = new javax.swing.JComboBox<>();
        Button_Convertir = new javax.swing.JButton();
        Resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Introduce Importe:");

        Importe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImporteActionPerformed(evt);
            }
        });

        Moneda_De_Importe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GTQ", "USD", "EUR", "PESO MX" }));
        Moneda_De_Importe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Moneda_De_ImporteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Convertir a:");

        Moneda_Conversion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GQT", "USD", "EUR", "PESO MX" }));
        Moneda_Conversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Moneda_ConversionActionPerformed(evt);
            }
        });

        Button_Convertir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Button_Convertir.setForeground(new java.awt.Color(0, 51, 204));
        Button_Convertir.setText("Convertir");
        Button_Convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ConvertirActionPerformed(evt);
            }
        });

        Resultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Importe))
                                .addGap(58, 58, 58))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Moneda_Conversion, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Moneda_De_Importe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_Convertir, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGap(34, 34, 34))))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Moneda_De_Importe, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Importe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Moneda_Conversion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Convertir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    Double cantidad = 0.0;
    Double conversion = 0.0;
    String de = "GTQ";
    String a = "GTQ";
    private void ImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImporteActionPerformed
    
    private void Button_ConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ConvertirActionPerformed
        DecimalFormat df = new DecimalFormat("#.00");
        cantidad = Double.parseDouble(Importe.getText());
        convertido();
        Resultado.setText(String.valueOf("resultado: "+df.format(conversion)));
    }//GEN-LAST:event_Button_ConvertirActionPerformed

    private void Moneda_De_ImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Moneda_De_ImporteActionPerformed
       de=Moneda_De_Importe.getSelectedItem().toString();
       convertido();
    }//GEN-LAST:event_Moneda_De_ImporteActionPerformed

    private void Moneda_ConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Moneda_ConversionActionPerformed
        a=Moneda_Conversion.getSelectedItem().toString();
        convertido();
    }//GEN-LAST:event_Moneda_ConversionActionPerformed
    public void convertido()
    {
        switch(de)
        {
            case "GTQ":
            {
                if(a.equals("USD"))
                {
                    conversion = cantidad*0.13;
                }
                else if(a.equals("EUR"))
                {
                    conversion = cantidad*0.12;
                }
                else if(a.equals("PESO MX"))
                {
                    conversion = cantidad*2.63;
                }
                else
                {
                    conversion = cantidad;
                }
                break;
            }
            case "USD":
            {
                if(a.equals("GTQ"))
                {
                    conversion = cantidad*7.67;
                }
                else if(a.equals("EUR"))
                {
                    conversion = cantidad*0.95;
                }
                else if(a.equals("PESO MX"))
                {
                    conversion = cantidad*20.18;
                }
                else
                {
                    conversion = cantidad;
                }
                break;
            }
            case "EUR":
            {
                if(a.equals("USD"))
                {
                    conversion = cantidad*1.05;
                }
                else if(a.equals("GTQ"))
                {
                    conversion = cantidad*8.08;
                }
                else if(a.equals("PESO MX"))
                {
                    conversion = cantidad*21.26;
                }
                else
                {
                    conversion = cantidad;
                }
                break;
            }
            case "PESO MX":
            {
                if(a.equals("USD"))
                {
                    conversion = cantidad*0.050;
                }
                else if(a.equals("GTQ"))
                {
                    conversion = cantidad*0.38;
                }
                else if(a.equals("EUR"))
                {
                    conversion = cantidad*0.047;
                }
                else
                {
                    conversion = cantidad;
                }
                break;
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculador_De_Divisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculador_De_Divisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculador_De_Divisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculador_De_Divisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculador_De_Divisas().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Convertir;
    private javax.swing.JTextField Importe;
    private javax.swing.JComboBox<String> Moneda_Conversion;
    private javax.swing.JComboBox<String> Moneda_De_Importe;
    private javax.swing.JLabel Resultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
